# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://nived-spacei.github.io/deck_of_cards/"

git_url = "https://github.com/nived-spacei/deck_of_cards/tree/{branch}/"

def custom_doc_links(name): return None
